### ISSUE TITLE
changing window scale doesn't do anything

### ISSUE THREAD

**Issue by foguetes** [stax76/mpv.net#105]
When I press the hotkeys Alt+0, Alt+1, and Alt+2 the window should change scale but it doesn't.

You can see it here: http://streamable.com/ny7pn

It should behave like this: http://streamable.com/e5swe

**Comment by stax76** [comment]
It's not yet implemented but will be likely in the next release.

**Comment by stax76** [comment]
I've implemented it but did it my own way. When Alt++ is pressed the current size is increased, when Alt+- is pressed the current size is decreased. I hope it makes sense.

```
 Alt++  no-osd set window-scale 1.2               #menu: View > Window Size > Enlarge
 Alt+-  no-osd set window-scale 0.8               #menu: View > Window Size > Shrink
```

**Comment by foguetes** [comment]
it doesn't really make sense to me, but it's ok as long as I can change it in the input.conf file
I tried adding those lines and it still didn't work, btw

**Comment by stax76** [comment]
It's available in the next release. I tried how it works in mpv with default settings and that didn't make sense to me, that's why I did it differently.

**Comment by stax76** [comment]
Please try this beta version:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by foguetes** [comment]
I tried it. It works only the first time after I unzip it and then it doesn't work anymore.

**Comment by foguetes** [comment]
oh, I thought the input conf file was included in the portable app folder. sorry
it works fine after after I rename the input conf file.
thanks!

**Comment by stax76** [comment]
mpv.net only creates mpv.conf, mpvnet.conf and input.conf when the files are missing. After that those files are never changed because they are important settings. You have to update those files manually! That's how the current design works, it might not be perfect but it's also not bad compared to other players which don't allow you to modify the menu and generally suck big time in areas like key bindings.

Defaults are here:

https://github.com/stax76/mpv.net/tree/master/mpv.net/Resources
