### ISSUE TITLE
Strange issue when 2 files selected in Windows explorer and press enter

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#108]
I have a strange behaviour that i could reproduce all the time:

open windows explorer. Select 2 video files (ONLY 2), press enter.
mpv.net opens with no OSD !!! 
Can someone check if they have the same, please?

my mpv.net is set to single instance mode.

**Comment by stax76** [comment]
Hello Vince,

I cannot reproduce it but it loads the folder which seems wrong. I'm researching it right now.

**Comment by stax76** [comment]
Apparently there is a clean and reliable way for implementing this using a shell extension (IDropTarget), I guess I will do this. 🙂

**Comment by 44vince44** [comment]
That's good news !!! and a good find. I can't wait to test a new beta!!

**Comment by stax76** [comment]
I've found C# sample code that is working but there are too many implications and too much complexity to integrate it. It could be implemented as external tool but at the moment I don't plan to do it.

Since I cannot reproduce it you could try using mpv.net default settings. You say there is no OSD, does that mean OSD is blocked for all commands? Or do you maybe mean OSC instead of OSD?

Do you have the folder auto load feature disabled (or press shift)? In the next build explorer multi select enter will work even when folder auto load is enabled (max 15 selections).

**Comment by 44vince44** [comment]
It is actually the OSC (sorry i got confused) that disappears. 
Folder auto load is DISABLED
All the commands are working but the OSC does not appear, even if I try toggling with DELETE key.

I made some more testing: this is NOT happening with the delfault settings. 
I reverted back to my personal settings, and set "start-threshold = 1500" and everything is working fine now.
So the problem was related to start-threshold which I had reduced to 100 because I don't use start-size = video.
So it seems that start-threshold must be 1500, it's better in all cases!
