### ISSUE TITLE
Request: Portable installation?

### ISSUE THREAD

**Issue by Pentaphon** [stax76/mpv.net#12]
I'd like something that runs from a single folder. No installation. No start menu entries. Or perhaps just a "portable mode" in the installer that creates the folder with everything in it and upgrades that folder on subsequent installs?

**Comment by stax76** [comment]
I consider it because it is a popular request. Why don't you like installation? I'm not seeing any real benefit.

**Comment by hubblec4** [comment]
Like I asked in Doom9 forum. A 100% portable version would be great.

**Comment by stax76** [comment]
> Like I asked in Doom9 forum. A 100% portable version would be great.

A portable download option is not a big problem technically, only a bit in regard of my principles, that's why I created a thread in the doom9 forum.

https://forum.doom9.org/showthread.php?t=176302

A different setting location does not work well with my design. One reason why it's complicated is there are currently 4 different apps involved. mpv, mpvnet, mpvConfEdit and mpvInputEdit and there is also mpvnet scripting and add-ons making it even more complex, the default location for scripts and add-ons is within the settings folder. It's not something I want to work on at this time but I will think about it in the future when I read or work on related things.

**Comment by Pentaphon** [comment]
@stax76 Because I'd like to put it on a USB stick, or I just don't want everything to be installed as a Windows application, or I want to run it on another person's PC without actually installing it.  I think it would be great to have an mpv.net folder and then a settings subfolder within the mpv.net folder.

**Comment by stax76** [comment]
Please help to test the new release:

https://forum.doom9.org/showthread.php?t=174841&page=7

**Comment by stax76** [comment]
release from today has a new feature:

portable mode: in case no config folder exists and the
startup folder has write access mpvnet will ask where
the config folder should be created (portable or appdata)

**Comment by MatejKafka** [comment]
I'd like to add a bit of reasoning for portable programs:

1) Typical Windows programs have very inconsistent data storage - some use HOME, others C:\ProgramData, others AppData\Local, others AppData\Roaming, others C:\Windows, others registry, others all of them at once. This makes it hard to figure out where all the app data are stored.

2) Another issue is that when reinstalling my system, I lose all my programs and configuration, because Windows cannot really know which folders to keep.

<hr>

I'm working a on Windows package manager that only uses portable apps, where each app has a single well-defined directory with separate subdirectories for the app itself, data, config, cache, logs,... This allows me to freely reinstall the system while keeping my setup exactly as it was. Another benefit is that it gives me more control over what the apps are doing to the system.

I think that in an ideal system, app setup should be strictly declarative; examples:
 - instead of an app setting itself as a handler for given file type, it should just declare that it supports the given file type and let system do the imperative part
 - instead of adding a task scheduler startup job (or using one of about 10 other existing mechanisms to run after startup), app should declare that it wants to run after startup, and system should handle it

Key point here is that the app should be unable to change anything outside its app directory; only thing it can do is to bundle a package manifest that basically says "hi package manager, if you're reading this, I'd like you to do these things for me", and it's up to the system to convert the app-local config into system state change.

<hr>

The advantage of portable apps here is that they typically allow much more control of their external behavior, so I and all the other nerds (with possibly completely different visions from mine) can make them behave as we want.
