### ISSUE TITLE
mpv.net doesn't respect no-keepaspect-window

### ISSUE THREAD

**Issue by fehrm** [stax76/mpv.net#123]
mpv.net doesn't understand --no-keepaspect-window and keepaspect-window=no doesn't change the behaviour of mpv.net

**Comment by vsub** [comment]
I was just about to ask about this.
Is there is a way to make mpv.net stretch the video to the window ignoring the aspect ratio

**Comment by stax76** [comment]
I consider adding this but I also want to do major improvements for staxrip and this will slow down mpv.net development much.

**Comment by stax76** [comment]
I don't understand for what `keepaspect-window=no` is useful.

**Comment by kg** [comment]
> I don't understand for what `keepaspect-window=no` is useful.

If I grab the top edge of a window and drag it to the top of the screen, Windows 10's desktop manager will 'snap' the window to the full height of the screen and preserve its current width. And if I drag a window to the left or right edge of the screen, Windows will 'snap' it to that edge, automatically increasing its height so that it takes up the entire left or right side of the monitor, and then I can drag the exposed horizontal edge to move the "split". This works for all well-behaved Windows applications and if you have an application on the other side of the "split", windows will resize it to prevent overlap when you move the split.

MPV.net's default behavior breaks everything except the initial snap-to-edge. If I snap a window to the left side of my monitor and try to widen it, MPV.net shrinks the window vertically, breaking the snap. If I drag the window's top edge to the top of the screen, mpv.net tries to make itself larger but somehow doesn't actually make itself wide enough to satisfy the aspect ratio constraint it's trying to enforce.

I think the default behavior is a reasonable compromise, but it's awkward and kind of busted, so it would be great if I could make the window behave like a regular window and use the w10 window manager with it like I do with everything else.

Sorry if I missed some obvious way to disable this behavior, all I found was a 2 year old reddit post about keepaspect-window, and then discovered this issue when trying to figure out which config file I would put the option in.

**Comment by soredake** [comment]
I hope this will be fixed....

**Comment by stax76** [comment]
There is a new beta version addressing this issue.
