### ISSUE TITLE
start-size

### ISSUE THREAD

**Issue by syfjhz22** [stax76/mpv.net#131]
Hi, I'm trying to make window size set to native video resolution for every vedio I click open. I can see the opition "start-size" in config editior, but even if I choose "video", the window size is still not video resolution size. I cannot find any option to scale window to native video resolution either.

Please help, thanks!

**Comment by stax76** [comment]
Maybe try the last beta.

**Comment by pintassilgo** [comment]
Hi. Still not working in 5.4.4.5.

**Comment by stax76** [comment]
Please fill out the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by pintassilgo** [comment]
**Describe the bug**
By default, mpv expands the video to its original size (or to the max screen size available). mpv.net doesn't do that, so I tried `start-size = video` (mpvnet.conf), but it doesn't work.

**To Reproduce**
Steps to reproduce the behavior:

1. Open mpv.net 5.4.4.5 (on my PC it opens in size 1120×630, while mpv opens in 962×512);
2. Config Editor > Screen > start-size > `[x] video`
3. Close mpv.net.
4. Open a video with high resolution.

**Expected behavior**
mpv.net should open with height = 1050px (max available space in my screen, since the video original height is greater than this value), just like mpv does.

But it seems that the maximum opening height is 840px. Tried videos with different aspect ratios and the height is always 840px.

**Screenshots**
Do you need this?

**Additional context**
Windows 10, 2560×1080 screen.

**Comment by stax76** [comment]
I hope it's all good in 5.4.4.6 Beta which is now available.

Sorry for the long time to fix it.

It's however a feature I don't understand, it would help me much if somebody could explain why to use `start-size=video` ?

Download it here:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

**Comment by stax76** [comment]
I've forgotten to mention that you need `autofit-larger=100`.

**Comment by pintassilgo** [comment]
Fixed, thank you.

> It's however a feature I don't understand, it would help me much if somebody could explain why to use start-size=video ?

I don't like to watch video in a smaller size that it should be. But I don't usually like fullscreen either. So ~2,35:1 videos should always expand to the maximum area by default, leaving only the 30px height Windows taskbar visible. If the video has smaller aspect ratio like 16:9 or 4:3 - remembering that my monitor is 21:9 -, then the video/player width shouldn't fill the entire width of the screen.

For the same reason, on browser I use the extension Maximize Video to expand videos (like YouTube) to the entire area of the page. It's almost as large as fullscreen, but without fullscreen downsides of hiding taskbar, tabs, urlbar.

By the way, what I'm going to say next is more something that should change in mpv side than in mpv.net: the player should consider `panscan` before setting initial window size.  4K Blu-ray videos (3840×2160) are opened on mpv/mpv.net with width of only 1863px, but they should fill the entire width (2560px) because I use `panscan=1` to hide black bars, so actually the video is ~2,35:1 (something like 3840×1636), not 16:9.

**Comment by stax76** [comment]
OK, thanks for the explanation.
