### ISSUE TITLE
Support --window-maximized=yes

### ISSUE THREAD

**Issue by zankai2** [stax76/mpv.net#142]
The latest version of mpv (0.32.0) introduced a setting called window-maximized.   Now mpv finally enters and exits fullscreen properly from a window.

It's much better than mpv.net's hackfix setting called maximized.   But mpv.net doesn't work at all with --window-maximized.   I tried looking at the source code; but I have no idea what needs fixing.

**Comment by stax76** [comment]
Why it's not working is explained here:

https://github.com/stax76/mpv.net/wiki/Limitations

The page says window-maximized is supported but since I implemented it just today it's not yet available, I'll let you know when I upload it.

My implementation seem to be reliable when it's used from mpv.conf and the command line but using it from input.conf with `cycle window-maximized` then it's only like 90% reliable and this is much likely a bug in the mpv client API and needs further investigation so please leave the issue open, I'll close it myself.

**Comment by stax76** [comment]
I've further investigated it and reported it on the mpv tracker, startup from cli and mpv.conf will work, input.conf works most of the time but not always, reason is unknown and very difficult to debug, users can use win+up and win+down instead of input.conf, I'll close the issue as soon as I upload a new build. Thanks for reporting.

https://github.com/mpv-player/mpv/issues/7611

**Comment by stax76** [comment]
Next build has:

- mpv property `window-maximized` support added, cycling it from input.conf
  might not be 100% reliable, use native Windows shortcuts Win+Up, Win+Down

For mpv developers it's difficult to fix because they would have to work with my source code, it's OK if nothing happens as long as the problem don't trigger other more serious issues. Using `window-maximized` on the command line and in mpv.conf will work in the next build, once uploaded I'll close the issue.

**Comment by stax76** [comment]
New beta version is now available:

https://github.com/stax76/mpv.net#beta
