### ISSUE TITLE
Fatal Error Can't find appropriate sample format AUDIO RELATED

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#162]
BUG specific to new mpv.net, that was introduced somewhere between 5.4.4.1 and 5.4.4.4, the last working version is 5.4.4.0. (In mpv original it works perfectly) :

When the following line is in mpv.conf: "audio-spdif=ac3,dts"
AND **computer has no spdif capabilities**
AND open a file with a ac3 or dts stream

Then there is an error :"Fatal Error" [ao/openal] Can't find appropriate sample format. And audio is not ouputted.

Expected behaviour : it should work, and audio should be dowmixed to standard output.
This is how it is done in mpv original, and in older versions of mpv.net.

**Comment by 44vince44** [comment]
I made further tests, I set "ao=wasapi" and I got the same error, but with wasapi instead of openal.

What changed between 5.4.4.0 and 5.4.4.4 in audio handling? I couldn't see anything in the commits...

**Comment by stax76** [comment]
It's very unlikely that audio handling was changed by me, if there is really something different, then it is likely a changed libmpv version.

If there is a message box that shouldn't be there then I can upload a new build. I made this change today:

mpv.net requests log messages from libmpv, the last build behaves like this:

If there is message with level fatal then mpv.net shows this message in the terminal or as message box depending on how mpv.net was started. I changed this to mpv.net not reacting on any log messages because libmpv already prints those messages to the terminal.

And I also changed which messages are requested, before it was level info, now I have changed it to use the same setting as defined by [--msg-level](https://mpv.io/manual/master/#options-msg-level) which is level status by default (some more messages than level info) so the user now can define which messages are requested.

But why does mpv.net request the messages and does nothing with it? It's for scripting and extensions. There is an event scripts and extensions can assign to receive the messages.

**Comment by 44vince44** [comment]
@stax76 The error message appears and the playback continues WITH AUDIO ! so I guess it's a message error that shouldn't be there indeed. Maybe you should upload this version!

**Comment by stax76** [comment]
I changed the release script to also output x86 betas.

5.4.7.1 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

Have you tried portable staxrip btw. ?

**Comment by 44vince44** [comment]
@stax76 I'm checking now for the "fatal" error.
What is staxrip portable ? I mean staxrip is always portable no?

**Comment by stax76** [comment]
> What is staxrip portable ? you mean avisynth portable ? is it in the latest beta ?

Yes, it's in the last beta, both avisynth and vapoursynth (and python) are now included and portable and enabled by default.

I tried your file and your setting, everything fine here. Maybe update your mpv as well as your libmpv file in mpv.net.

https://sourceforge.net/projects/mpv-player-windows/files/

**Comment by 44vince44** [comment]
@stax76  what does mpv has to do here ? I don't understand, I used your last beta full archive ?

**Comment by stax76** [comment]
> because **mpv** automatically detects that there is no spdif and overrides this option. So **mpv.net** must not freeze.

To be sure that mpv and mpv.net behave differently you have to use mpv and libmpv in mpv.net from exactly the same built date.

**Comment by 44vince44** [comment]
I tried it before posting :-))) obviously

**Comment by 44vince44** [comment]
I'm investigating more... because i just tried on a default mpv.conf (mpvnet) and adding the line audio-spdif=ac3,dts worked. So I guess I got messed up and soeting in my conf is not good... I think I did something early this morning, checking now

**Comment by 44vince44** [comment]
@stax76 My mistake !!! I have been working on other things this morning, so meanwhile i made something wrong:
- the fatal error message of yesterday is gone
- the freezing in version 4.5.7.1 it was my fault, I was working on things such as thumbnailer etc, and i did something wrong, so i restored mpv.conf to my backup, and it works fine!

**Comment by stax76** [comment]
No problem. 🙂
