### ISSUE TITLE
Hotkey while the mpv.net-player is minimized or in background.

### ISSUE THREAD

**Issue by Squishfish** [stax76/mpv.net#172]
_First of all thank you very much for the best player I've ever used. Your version enables even an average user like me to use and share it with non computer-savvy friends. And also thank you very much for this genious "play with mpvnet server" programm. It just enables me to play youtube videos while playing on my old old half step in grave computer._

The only thing I would like to ask / request: Is it possible to have **globaly working Hotkeys** while the **player** is in the **background or minimized**? For example if I play a game and want to mute or pause the player, my media keys don't work. They only work when the player is "focused". 

So something like to **choose** any **Hotkey** to be **global**, default not global would make sense I guess?

I actually tried to make it with Autohotkey (AHK), but since i have no idea I failed miserably with zero results.

**Comment by stax76** [comment]
I'll be working on this soon.

**Comment by TheFireRed** [comment]
I've been using StaxRip for many years and I was quite pleased to find out you were also maintaining an mpv media player. I decided to switch from mpc-hc to mpv.net today, but was shocked to find that media controls don't work while the window isn't focused, as mpc-hc and Win10 default player do. I'm glad to see this issue was opened recently and that you're already working on it. :)

**Comment by 44vince44** [comment]
@stax76 I guess that if you're gonna implement it, there would be an mpvnet.conf entry for enabling it. Although this is a very good idea, some people will still prefer to have the media keys working only on the focused window.
For instance, when you use multi-instance mode, you wouldn't like to have all the instances played and paused when you press the pause multimedia key.

**Comment by TheFireRed** [comment]
Yup! As long as we've got options, we all win.

**Comment by stax76** [comment]
I will probably first look what other players do, what tools like auto hotkey can do. Most likely it will be an option in the config editor and in mpvnet.conf, a C# script would be another option.

I've already experience with this from a retired personal tool, code unfortunately lost and from another personal tool still in use, that is a keyboard driven launcher I plan to release, I use it since many years, will hopefully be more successful than Open with++ and MediaInfo.NET. It's different from wox and keypirinha, new powertoys have also something similar, not tried yet.

I think there are two different APIs for this, one is a little more difficult (hooks), it's the code I lost, maybe few hours to rebuild, the other is total easy and will hopefully work and be sufficient.
