### ISSUE TITLE
mpv.net crashes suddenly

### ISSUE THREAD

**Issue by H4mmaster** [stax76/mpv.net#174]
**Description**
The player crashes whenever I play a video. Sometimes it crashes after a few seconds, sometimes it runs fine but crashes if I quickly change the volume or skip around the video. When I ran it from the command prompt it printed out:
[ao/wasapi] Under-run: Device delay: -0.7 us
[ao/wasapi] Under-run: Device delay: -0.7 us
just before crashing.
It might be related to this: https://github.com/mpv-player/mpv/issues/6134 although regular mpv works fine and I wasn't using whatever script that guy was. However like that issue, the problem seems to go away if I run it with --no-config.

**mpv.conf**
input-default-bindings = no
input-ar-delay = 500
input-ar-rate = 20
keep-open = yes
keep-open-pause = no
osd-duration = 2000
osd-playing-msg = '${filename}'
script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,console-scale=1,5
screenshot-directory = '~~desktop/'
hwdec = yes
.# Editor (added the . because otherwise the # turned it into a title)

hr-seek = yes (the only non-input option I changed, reverting it back to default doesn't fix the issue)

[protocol.https]
osd-playing-msg = '${media-title}'

**To Reproduce**
I don't really know how you'd reproduce it since most people don't seem to be having this issue. I will say that I'm using the latest version of the .net framework, 64 bit windows 10 and I'm running it on my laptop with a 5th generation intel cpu and intel hd graphics 5500.

**Expected behavior**
Well I expect it not to crash.

**Comment by stax76** [comment]
> the problem seems to go away if I run it with --no-config.

And if you rename mpv.conf so that libmpv cannot find it, is it then stable? If so then you can disable the options one by one to find out which one triggers the issue.

> .# Editor (added the . because otherwise the # turned it into a title)

I don't understand, the hash symbol starts a comment, a comment shouldn't have any effect.

**Comment by H4mmaster** [comment]
When I renamed mpv.conf to something else it just made a new one when I launched a video and the problem remained. However I did go through the file disabling the options one by one and it seems the problem was caused by hwdec. Setting that to "no" fixed it. Thanks for your help. I should mention that I tried playing an .mp4 file and that worked fine even with hwdec enabled, the issues I had were with .mkv files.

Also I seem to have confused you with the dot, it didn't cause problems in the file, I just added it because github made the line into a title if I didn't put a something in front of it. The dot isn't present in the file itself.

**Comment by stax76** [comment]
Maybe the Intel support of mpv or ffmpeg isn't very good or it's a driver issue.

You can use the mpv tracker for it:

https://github.com/mpv-player/mpv/issues

I've had different NVIDIA cards and hwdec is 100% stable with it, it's in particular useful for 4K files, for normal HD files software decoding is fine.

**Comment by SonaliBendre** [comment]
@stax76 the same is happening with me. sometimes it suddenly freezes and altho the video plays perfectly, i cant close/minimize mpv.net, no OSD and mpv.net options work

**Comment by stax76** [comment]
How often does it happen? Did you try different settings or logging? I don't know your specs.

**Comment by SonaliBendre** [comment]
mostly when playing heavy h264 remux/web-dl untouched type videos(i.e. big files about 9 GB/30 min. or 35 GB/2hr.) with rclone mount. Only happens if I try to open context menu by right clicking, even the shortcut keys/osc works and cant click anything or close mpv.net, the video still plays without any issue. Sometimes by waiting for sometimes or clicking on mpv.net window it becomes normal again. By the way, if I let the video play for sometimes freely without interruption, it open Context Menu and other options work without any issue, it mostly happens if I try to open Context Menu or try click other options like play/pause as soon as opening mpv.net. Its not my hardware or network issue(even if rclone collects 1 minute cache of the video it still freezes), I had tried in my windows server and freeze there also.

**Comment by stax76** [comment]
It's much likely GPU related. What GPU is it and is an up to date driver installed?

You can try `gpu-api=opengl`.

**Comment by SonaliBendre** [comment]
still same. i guess its cache issue of bigger files than gpu related because it mostly doesn't accept my any inputs and freezes when I try to open Context Menu by right-clicking when mpv.net just starts playing video with less cache.
By the way i mostly play video by mounting my drive with rclone which uses winfsp https://rclone.org/commands/rclone_mount/

My mpv.conf i.e. mpv.net settings

`
input-default-bindings = no
input-ar-delay = 500
input-ar-rate = 20
keep-open = yes
keep-open-pause = no
osd-duration = 2000
osd-playing-msg = '${filename}'
script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,console-scale=2.5
screenshot-directory = 'somewhere'
# Editor
save-position-on-quit = yes
screenshot-format = png
screenshot-tag-colorspace = yes
screenshot-high-bit-depth = no
screenshot-template = '%f-%wH.%wM.%wS.%wT-#%#00n'
screenshot-png-compression = 9
gpu-api = opengl

[protocol.https]
osd-playing-msg = '${media-title}'
`
by the way i tried updating my gpu driver but it says
![image](https://user-images.githubusercontent.com/73757361/133918339-0d5c3cb1-6e02-4488-acc7-014e1e25de29.png)

**Comment by stax76** [comment]
So it happens only when using rclone?

**Comment by SonaliBendre** [comment]
yes and also when playing videos from url. i think its cache issue

**Comment by stax76** [comment]
It's too difficult for me to reproduce.

See if logging shows a problem:

https://mpv.io/manual/master/#options-log-file

Start mpv.net from the terminal and see if it prints errors on the terminal.

**Comment by SonaliBendre** [comment]
here's the log file - https://rentry.co/9v4te/raw

the terminal output : -

` (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) 'DTS-HD MA 7.1' (dts 8ch 48000Hz)
     Subs  --sid=1 --slang=eng (*) (f) 'English (Forced only)' (hdmv_pgs_subtitle)
     Subs  --sid=2 --slang=eng 'English (SDH)' (hdmv_pgs_subtitle)
     Subs  --sid=3 --slang=dan 'Danish' (hdmv_pgs_subtitle)
     Subs  --sid=4 --slang=dut 'Dutch' (hdmv_pgs_subtitle)
     Subs  --sid=5 --slang=fin 'Finnish' (hdmv_pgs_subtitle)
     Subs  --sid=6 --slang=fre 'French' (hdmv_pgs_subtitle)
     Subs  --sid=7 --slang=ger 'German' (hdmv_pgs_subtitle)
     Subs  --sid=8 --slang=nor 'Norwegian' (hdmv_pgs_subtitle)
     Subs  --sid=9 --slang=swe 'Swedish' (hdmv_pgs_subtitle)
File tags:
 Title: Free Guy
AO: [wasapi] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
(Buffering) AV: 00:00:06 / 01:54:58 (0%) A-V:  0.000 Dropped: 3 Cache: 0.3s/1MB
[input] No key binding found for key 'MBTN_LEFT'.
(Paused) AV: 00:00:37 / 01:54:58 (1%) A-V:  0.000 Dropped: 31 Cache: 11s/46MB
[input] No key binding found for key 'MBTN_LEFT'.
^Caused) AV: 00:00:37 / 01:54:58 (1%) A-V:  0.000 Dropped: 31 Cache: 34s/150MB`

Let me reproduce it again clearly.
Play a video from folder (which is mounted using rclone). the video plays for 10-20 seconds and I try to open Context Menu (by right-clicking) then although the video still plays, I lost control to mpv.net. Can't use any shortcut keys or play/pause or close mpv.net.
