### ISSUE TITLE
Prefer youtube-dl on path over the one in mpv.net location

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#175]
**Describe the bug**
Twitch does not work in the version of youtube-dl present in mpv.net, but I have the latest version in my path already, which does not have this issue.

**To Reproduce**
Open any twitch link on latest mpv.net (5.4.8.0)

**Expected behavior**
mpv.net should use the youtube-dl present on path over the one on mpv.net location.

**Comment by Restia666Ashdoll** [comment]
Interesting. I just submitted a pull request for mpv.net in Windows Package Manager. So, I wonder if the Inno installer can have a flag to exclude youtube-dl and update tools(update.ps1 and 7zip, because you will use winget to update) from the installation.
Although the latest 64-bit installation is tagged as malware by the Microsoft Defender SmartScreen and the uninstaller does not work.

**Comment by stax76** [comment]
The reason for why the included youtube-dl is used is probably windows default search behavior and not something hard-coded in mpv.net or libmpv. 

Workaround would be users just deleting the included youtube-dl, maybe that's OK or maybe there are other things that could be done better, I have to think about it.

I don't think it's a big problem however because workarounds exist, and they are easy to find out and apply.

**Comment by Restia666Ashdoll** [comment]
@stax76 How about the installer having the option to exclude youtube-dl and update tools? I think I should make this and other issues with the installer(like uninstaller does not work) as a separate issue.

**Comment by stax76** [comment]
It's a possibility.
