### ISSUE TITLE
Is there any kind of data being sent over the internet?

### ISSUE THREAD

**Issue by abh-oss01** [stax76/mpv.net#187]
Is there any sort of telemetry, or any kind of data being sent to the Dev, over the internet?
For eg: The files played, list of files, names, the actual content played, etc..? 

If yes, please elaborate, and please provide the steps to disable it and disable all local logging too. I know media players keep a log for files played locally, players like VLC give an option to disable keeping these recent file logs.

If no, please prove it to me. 

I am really sorry, I am not doubting the Dev's work or the team behind this **amazing project**, I'm just trying to understand this in a better way.

**Comment by stax76** [comment]
mpv.net does not send any data.

It makes a request in order to find out if there is a new version, this is only incoming data, there is a setting in the conf editor for this and I think it's disabled by default.

I don't know if by default libmpv sends any data, I doubt it, for that you have to ask on the mpv tracker.

There is a local history feature, if the menu _Tools > Show History_ is invoked, mpv.net will ask to create the file `<settings>\history.txt`, if the file exists then opened media is logged in this file.

For the recent menu there is a setting in the conf editor called recent-count.

I'm not experienced in this area but I think if you want to ensure apps not sending data you have to use a firewall.

**Comment by abh-oss01** [comment]
Thank you so much for this thorough clarification.

>if libmpv sends any data by default?

for this, should I open a question ticket on the upstream mpv repo? or you will revert back to me here after you get any clarifications from upstream?
