### ISSUE TITLE
Does mpvnet support multiple audio devices?

### ISSUE THREAD

**Issue by gralsean16** [stax76/mpv.net#213]
In mpv.io there's a command called --audio-device that sets the audio device to be used by the player. I was wondering if mpv.net has something similar.

I tried using Windows 10's built in audio properties to set the device, but it only works when it's playing a file (and closing the player resets it).

**Comment by gralsean16** [comment]
So it turns out the command can be used in mpv.net but "--audio-device=help" does not; in mpv.io, this list the audio devices which is to be used in "--audio-device". I have to use mpv.io to get the device label.

**Comment by stax76** [comment]
This =help convention is not provided by libmpv I think, it might be too much work to replicate such things.

Two things you can do at the moment:

1. Write script/extension to make it more convenient.

2. Open the [OSD console](https://mpv.io/manual/master/#console) by pressing back tick in order to print the [audio-device-list](https://mpv.io/manual/master/#command-interface-audio-device-list) property on screen:

`print-text ${audio-device-list}`

If mpv.net was started from the terminal then it's printed on screen but also in the terminal.

It's not very user-friendly, so I change the tag from _question_ to _feature request_.
