### ISSUE TITLE
5.4.8.5: PCM Audio from Blu-Ray Iso/m2ts Audio Broken

### ISSUE THREAD

**Issue by DReaper** [stax76/mpv.net#217]
**Describe the bug**
When playing a BD .iso or .m2ts file, no PCM audio track plays. I can confirm that it plays fine in 5.4.8.4. 

**To Reproduce**
Load any BD .iso or .m2ts file into mpv.net. The video plays with no issue but no audio.

**Expected behavior**
Audio to play.

**Comment by stax76** [comment]
Probably this:

https://github.com/mpv-player/mpv/issues/8375

You have to wait until shinchiro makes a new build.

**Comment by 44vince44** [comment]
It looks also DTS and DTS-HD is broken...  everything worked fine when I put the older mpv-1.dll instead of the new one.

**Comment by stax76** [comment]
I don't know if I have an image with PCM, DTS plays fine here however but DTS XLL isn't found.

A: German, DTS XLL, 2 098 kb/s, 6ch, 48.0 kHz, Default
A: German, DTS, 1 509 kb/s, 6ch, 48.0 kHz
A: English, DTS XLL, 2 224 kb/s, 6ch, 48.0 kHz
A: English, DTS, 1 509 kb/s, 6ch, 48.0 kHz
A: English, DTS, 384 kb/s, 2ch, 48.0 kHz

**Comment by 44vince44** [comment]
It appears my problem is different, it was related to  audio-spdif=ac3,dts setting. 
I also created a bug report on their tracker for that.

**Comment by 44vince44** [comment]
@stax76 @DReaper the new build by shichiro is out https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

Check if it fixes you issue. It didn't fix mine :-(

**Comment by DReaper** [comment]
> 
> 
> @stax76 @DReaper the new build by shichiro is out https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
> 
> Check if it fixes you issue. It didn't fix mine :-(

It fixed the issue on PCM audio.

DTS and DTS-HDMA was always working for me on the older version so I can't comment there.

**Comment by stax76** [comment]
I thought DTS-MA with core would show as two tracks like using MKV.

**Comment by 44vince44** [comment]
my issue is different, it turned out to be related to the audio-spdif=ac3,dts switch. I actually filed a bug report on their mpv's git.

**Comment by 44vince44** [comment]
@stax76 

> I thought DTS-MA with core would show as two tracks like using MKV.

No, DTS-HDMA is a single track. Its architecture is core+additions bitstreamed to 1 track ONLY, allowing compatibility with all receivers: older receivers will get the stream, and only process the core because it's the only thing they understand. Newer receivers will process the whole core+additions.

When you have two streams, its either because:
BD release includes on purpose a DTS track as second track, but that would be stupid (except if not exactly the same material, i.e another language, includes commentaries, different mastering of music,...) 
or
the popular software (I don't want to name it) used to extract from the BD has extracted the full stream and extracted the core for user's convenience and put them as two different streams (which is also not really clever, because keeping the full stream will work in all cases).

Did I answer your question?

**Comment by stax76** [comment]
@44vince44 It's very clear now, thanks.

I had forgotten it's just one stream in a transport stream.

mpv shows DTS and not DTS-MA, mpv.net gets the data using following property:

https://mpv.io/manual/master/#command-interface-track-list/n/codec

But I'm personally not really concerned, does not really make a difference for me...
