### ISSUE TITLE
Please consider the following changes to installer

### ISSUE THREAD

**Issue by asianmusicguy** [stax76/mpv.net#243]
1. allow user to add desktop shortcut during installation process
2. allow user to choose configuration path during install instead of first open along with recommending your preferred  location

**Comment by asianmusicguy** [comment]
@stax76  would these changes be hard to implement ? they would be so helpful

**Comment by stax76** [comment]
Please fill it out:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen and how it should work.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Explain why the feature matters to you**

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by asianmusicguy** [comment]
is your feature request related to a problem? Please describe.
Yes the installer package should give the user the option to automatically place a shortcut to the main exe on the desktop
Describe the solution you'd like
A clear and concise description of what you want to happen and how it should work.
add a check box to the installer file that says "add shortcut to desktop?" and then if clicked the installer does so
Describe alternatives you've considered
its just really abnormal not to be included

Explain why the feature matters to you
it is a basic function and expected option for most program installs to add a shortcut to desktop

**Comment by asianmusicguy** [comment]
2
is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Yes The configuration file location is chosen on first open of mpv.net.exe
 
Describe the solution you'd like
A clear and concise description of what you want to happen and how it should work.
a dialogue should appear during installation that says
Please chose save location for configuration files:
followed by the options 
1
2
3
this is so that users dont have to set it on first open which seems odd and a step many users would miss
 
Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Explain why the feature matters to you

it eliminates confusion for users
