### ISSUE TITLE
i'm not able to set italian language

### ISSUE THREAD

**Issue by p060477** [stax76/mpv.net#305]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
hi, i'm not able to set italian language...could you pls help me..?'
thxs in adv!
cheers

**Comment by stax76** [comment]
Only English is supported because mpv is an elite/nerd player which understand English well.

Users can learn English using the Google Translator, the web interface allows to export the favorites to Google Sheets which allows saving as CSV which can then be imported in Anki, or premade English decks for Anki can be used:

https://ankiweb.net/shared/decks/english

Search Anki tutorials with Google and YouTube.

**Comment by p060477** [comment]
thxs so much for yr prompt reply!
so sorry....
consider also an italian trad in future..as for ex:
mpv-easy player which is also based on mpv,the you called elite/nerdy...,
but has also the ita lang included...
;)
