### ISSUE TITLE
Issue with mpv.net when opened from staxrip

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#36]
Dear Stax, this is an issue I posted in the Staxrip issue page, and Revan asked me to post it here:

in older staxrip like 1.7.0.6, when I open preview window and press E to preview in mp.vnet, the preview showed video and played the audio track also.

Now with recent Staxrip, the preview only plays video, no audio.
It was good to have audio, very useful. So is it a mpv problem?

**Comment by 44vince44** [comment]
I confirm = I made a test putting the old mpvnet 0.2.2 in the proper app folder of staxrip.
In staxrip: preview, press E, mpvnet 0.2.2 launches but gives errors (expected), the mpvnet 0.2.2 plays video WITH AUDIO.
So something changed in mpvnet, which makes it not play audio of staxrip avs previews. And this change is at least since mpvnet v2.0.0.0

**Comment by stax76** [comment]
I believe old libmpv versions did except the property audio-file and new versions don't. Next mpv.net version will show an error message when invalid command line arguments are passed. I tried to use audio-files-append but it did not work but audio-files works, so I will fix staxrip to use audio-files instead of audio-file.

**Comment by 44vince44** [comment]
Thanks Stax !!!
