### ISSUE TITLE
Microsoft Store versions does not create config in %APPDATA%

### ISSUE THREAD

**Issue by A-tG** [stax76/mpv.net#366]
If there is no %APPDATA%/mpv.net folder the program will store settings somewhere else (probably in %LOCALAPPDATA%/Packages) and will ignore manually created folder with config in %APPDATA% until reinstalled.

**Comment by KaranKad** [comment]
mpv.net does not create a config folder automatically but will look for one at `%appdata%\mpv.net` or at `%localappdata%\Packages\5664FrankSkare.mpv.net_0ta2kwwjvkgap\LocalCache\Roaming\mpv.net` for msstore or whichever exists or is created first. Since i migrated from mpv.net released from github to msstore it automatically picked up config from `%appdata%\mpv.net`. If you want mpv.net to read config from `%appdata%\mpv.net` move and delete everything from `%localappdata%\Packages\5664FrankSkare.mpv.net_0ta2kwwjvkgap\LocalCache\` and put it in `%appdata%\mpv.net`

**Comment by A-tG** [comment]
The problem is it's not mentioned anywhere and "Open Config Folder" tries to open folder that does not exist. This creates confusion, I had to figure it out that msstore apps have their own "appdata" folder.

**Comment by stax76** [comment]
The next version uses powershell for the folder creation, hopefully this will fix the issue entirely, it worked in my tests.

```C#
using (Process proc = new Process())
{
    proc.StartInfo.UseShellExecute = false;
    proc.StartInfo.CreateNoWindow = true;
    proc.StartInfo.FileName = "powershell.exe";
    proc.StartInfo.Arguments = $@"-Command New-Item -Path '{_ConfigFolder}' -ItemType Directory";
    proc.Start();
    proc.WaitForExit();
}
```

**Comment by stax76** [comment]
I've tried 5.7.0.0 from the store on my notebook today, the powershell fix works.
