### ISSUE TITLE
Publish beta version on github?

### ISSUE THREAD

**Issue by zhongfly** [stax76/mpv.net#375]
The last github release was in May 2021,I think it's time to publish a pre-release on github if you don't want a new "Latest release".
Publishing a pre-release on github also means it's a beta version, and it also won't be marked as "latest" by github.

**Comment by stax76** [comment]
It's more convenient for me to use the cloud drives because it's only a file copy operation which can be scripted easily.

GitHub can be scripted as well, I guess, hopefully it's not too difficult.

What are the advantages of using GitHub? It might be easier to find for users and maybe notifications, anything else?

I will think about it and try to upload it in 1-2 days.

**Comment by zhongfly** [comment]
For me, it's easier to find updates, and github has notifications.
You can try https://cli.github.com/ ,it is GitHub’s official command line tool.

**Comment by stax76** [comment]
I've manually uploaded it now:

https://github.com/stax76/mpv.net/releases
