### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by maggotb** [stax76/mpv.net#390]
![Sans titre](https://user-images.githubusercontent.com/62154223/159162076-3e5a8889-d69a-460b-9c3d-c96bc9e25420.png)

I unzip the latest 5.7.0.0 release, open mpvnet.exe and this is what happens. "the file can"t be found" I'm on Windows 7.
Any way to fix this ? thanks

**Comment by stax76** [comment]
It's missing PowerShell 5.1, there is new PowerShell code used because it bypasses appdata file location virtualization in the MS Store version, this code executes in the non-Store version too. This will be fixed in the next build, you can work around it by creating a folder here:

C:\Users\%USERNAME%\AppData\Roaming\mpv.net
