### ISSUE TITLE
Multilanguage GUI - Please add it

### ISSUE THREAD

**Issue by bovirus** [stax76/mpv.net#399]
@stax76 

**Is your feature request related to a problem? Please describe.**
Please add option to localuize GUI

**Describe the solution you'd like**
To have multiple language for GUI

**Describe alternatives you've considered**

**Additional context**

**Comment by hooke007** [comment]
dup https://github.com/stax76/mpv.net/issues/75

**Comment by stax76** [comment]
It would need a complete new design, which makes only sense if you go cross-platform, that is a gigantic project, far too difficult at the moment.

**Comment by stax76** [comment]
Multilanguage is unrealistic for me when running the project alone because there would be too many requests. Sometimes I ask myself, however, if I should open mpv.net up for collaboration, then multilanguage would probably be doable. If it makes sense is another question. I'm certainly aware that learning English is no easy task.
