### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by GitNaufal** [stax76/mpv.net#404]
All 2022 releases had a random stuttering issue.
Last 2021 release, which is 5.4.9.0, doing very smooth.
Weird...

---
### Settings
- Default

---
### Specs
- i7 8750H
- 1070 Max-Q
- Windows 11

**Comment by stax76** [comment]
Try the old libmpv DLL of 5.4.9.0 in the current mpv.net version, just replace the DLLs.

**Comment by GitNaufal** [comment]
> Try the old libmpv DLL of 5.4.9.0 in the current mpv.net version, just replace the DLLs.

**Solved**, thanks.
- Rename 5.4.9.0's DLL from mpv-1.dll to mpv-2.dll
- Replace 5.7.0.0's DLL with 5.4.9.0's DLL

**Comment by stax76** [comment]
It means however you are stuck with an old library. Maybe the new library would work with changed settings.

**Comment by GitNaufal** [comment]
I think the issue is not because of the mpv-2 build.
I tried [mpv-1 latest build](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220401) & [mpv-2 early build](https://github.com/zhongfly/mpv-winbuild/releases/tag/2021-12-31)  by zhongfly, and mpvnet is still random stuttering, even worse.

Any advice that I can try?

**Comment by GitNaufal** [comment]
I'm stuck with the [mpv-dev-x86_64-20210919](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) built by shinchiro.
Above this version will cause random lagging.

**Comment by stax76** [comment]
Are you mostly using default video settings? Please post mpv.conf in case you changed video conf options. It's fine to investigate this here, but since it's due to a change in libmpv, you can also create a ticket on the mpv tracker, mpv devs working on video processing are best suited to help with this.

Commit history for this date is here:
https://github.com/mpv-player/mpv/commits/master?after=2cafe5137f1544df130face8f748cc571ddf0445+314&branch=master
