### ISSUE TITLE
Crash when clicking chapter track 

### ISSUE THREAD

**Issue by User-3090** [stax76/mpv.net#443]
When chapters are only available in a single language, click the corresponding track in the context menu crashes the player. Also, could it maybe display the chapter language in the menu entry? 

![2022-06-16 12_10_17-](https://user-images.githubusercontent.com/71881005/174048096-b343c31b-69f0-4d75-8738-6171ca237a56.png)

**Comment by hooke007** [comment]
E —— edition
There is no chapter in your example file.
https://github.com/stax76/mpv.net/issues/421#issuecomment-1132279304

**Comment by stax76** [comment]
@User-3090 

The crash is fixed in v6.0.0.0 Beta, which is the last release. Here it caused a freeze, so it's rather severe, and I will try making a stable release next week.

> Also, could it maybe display the chapter language in the menu entry?

Is it supported by mediainfo? In mpv it doesn't seem to be supported.

https://mpv.io/manual/master/#command-interface-chapter-list

https://mpv.io/manual/master/#command-interface-edition-list

Is what you see, maybe the title? But that should already be supported.
