### ISSUE TITLE
Crash when playing back AV1 files with grain synth

### ISSUE THREAD

**Issue by banjaminicc** [stax76/mpv.net#482]
**Describe the bug**
As mentioned
The player throws a Visual C++ runtime error when playing back av1 files that have grain synth

```

 Assertion Failed
File ../../../../../src_packages/libp.../film_g...n_av1.c

Expression : shift >= 0

```

**To Reproduce**
Play any av1 file that has grain synth

1. mpv.net version : Recent ones (i.e from these few months)
2. Windows version : Tested on both W10 and W11
3. GPU name : RTX 3060

**Comment by stax76** [comment]
You can report it on the ffmpeg bug tracker.

**Comment by banjaminicc** [comment]
> I'm not sure where this can be reported, ffmpeg maybe.
> 
> https://trac.ffmpeg.org

However stock mpv and ffplay both play the video normally
Is this not an issue of mpv.net?
Or should I look at the ffmpeg libs that I've placed in system path?
Do those matter

**Comment by banjaminicc** [comment]
@stax76 Figured out the issue
When using auto-copy hwdec it crashes
But as long as I specify other methods like nvdec/d3d11va etc it works fine
Seem to be an issue with a specific hw decoder

**Comment by phorensic** [comment]
I know this issue is closed, but I encountered this bug also.

I fixed it with: `vd-lavc-film-grain=cpu`

My relevant and working config options:
`vo=gpu-next`
`vd-lavc-film-grain=cpu`
`gpu-api=opengl`
`hwdec=nvdec`

If loading an AV1 with film grain synthesis encoded AND `vo=gpu-next` to enable that functionality, then the crash described in the OP will occur when trying to load the film grain module. I found this is because if `vd-lavc-film-grain` is not set, which assumes `vd-lavc-film-grain=auto` then it chooses `vd-lavc-film-grain=gpu` and crashes. Also, if explicitly set to `vd-lavc-film-grain=gpu` it crashes. Only if `vd-lavc-film-grain=cpu` will everything run fine on my machine.

My setup:
- mpv.net v6.0.3.2-beta
- Windows 11 22H2 22623.870
- Nvidia 3050 driver 522.30

Looking through verbose logs and trying to debug myself, I'm not sure who is to blame or what github repository to also file this bug. Could be mpv.net, mpv vanilla, libplacebo (ffmpeg?), or even dav1d.
