### ISSUE TITLE
Running mpv.net for the first time on a Windows 7 machine with a dark theme = unreadable text

### ISSUE THREAD

**Issue by floppyD** [stax76/mpv.net#54]
Maybe checking if the registry theme color string returns pure black and setting it to white automatically would solve the issue? Or just making black/white invalid colors for dark/white themes respectively.
![mpv net 4 7 7 0](https://user-images.githubusercontent.com/29208110/61911306-827a4e80-af0d-11e9-9ea5-3710b4244647.png)

**Comment by stax76** [comment]
Are you using 4.7.7 ?

https://github.com/stax76/mpv.net/releases/tag/4.7.7

4.7.7 changlog:

on Win 7 the theme color was hard coded to DarkSlateGrey because
WPF was returning a bad color on Win 7, this was fixed by reading
the theme color from the Registry on Win 7. **If the theme color
is identical to the background color it's corrected**

**Comment by floppyD** [comment]
I am, I had just installed it actually. That's how it looked like on the first run.

**Comment by stax76** [comment]
Maybe I have to set defaults for dark-color and light-color and not use the theme color by default.

I would have to make a decision which default colors to use, I'm open to suggestions.

I hope I don't have to rewrite the setting infrastructure and if so that it's not difficult.

Thanks for the feedback.

**Comment by floppyD** [comment]
White/Black sounds good as default colors imo

**Comment by stax76** [comment]
Next release has two default colors, if the file mpvnet.conf is missing then this file is created with these two colors. Thanks for the feedback.

![Untitled](https://user-images.githubusercontent.com/11410540/61986221-fef45680-b00d-11e9-86a0-2f6e4bbf2b50.png)

**Comment by floppyD** [comment]
That's nice too

**Comment by stax76** [comment]
The new release is out.
