### ISSUE TITLE
use of direct3d not recommended

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#6]
Dear Stax, a few days ago, you were discussing that hwdec=yes, vo=direct3d is what you use.
But, i made several tests, and i found that vo=direct3d does not allow the colormatrix information to be applied.
When you use vo=direct3d, the video will always be decoded as bt.601, even if you change it, mpv accepts the command, the display will show colors that match the bt.601.
(means : magentas very strong, greens not good)

I found that the proper way to handle that is:
vo=gpu,
hwdec=no

hwdec=no because if set to yes, i get crashes when seeking.
the comma after gpu is for compatibility with older mpv.net that work with your last staxrip 1.7.0.6 that i still use.

**Comment by stax76** [comment]
Hi,

there are a few properties/settings mpv.net sets on startup:

https://github.com/stax76/mpv.net/blob/master/mpv.net/mp.cs#L93

I don't remember all of them but I remember the two you mention I think.

hwdec is absolute stable here using NVIDIA GT 1030, I agree that changing this default might not be the best idea so yes I might change this back to mpv default, may I ask which GPU you use?

I changed vo because the default don't work when the display is duplicated which I always do, again changing this default might not be the best idea and I might change it back to mpv default, probably that's less confusing.

**Comment by stax76** [comment]
I plan to remove the modified settings from the mpv.net code and write it to the mpv.conf file instead in case no mpv.conf file exists, this way it's more transparent to the user.

**Comment by 44vince44** [comment]
Yes it's a good idea. User can expect same behaviour as mpv.net and doesn't get confused ;-)
