### ISSUE TITLE
ClientMessage Scripts firing 4 times

### ISSUE THREAD

**Issue by SLowrAM** [stax76/mpv.net#60]
I upgraded from v4.4 to 5.0 (sometime after v4.4) .cs scripts like the sample Adding A Keybinding are now firing 4 times.

**Comment by stax76** [comment]
What did you download, setup or portable, 32bit or 64 bit?

**Comment by SLowrAM** [comment]
64 bit portable "mpv.net-portable-x64-5.0.0.0.7z".

**Comment by stax76** [comment]
Did you copy the new folder over the old folder? I renamed the script host extension, probably you have more than one script host extension.

**Comment by SLowrAM** [comment]
I did copy over (copied over subfolders too), but going from 4.4 to 5.0 the old folder was Addons vs the new Extensions.  I deleted Addons folder.  If I copy and replace MPVNet.exe and .pdb with 4.4 1 fire, go back to 5.0 and 4 fires.

**Comment by SLowrAM** [comment]
I have it installed at c:\mpvnet and told it to use that as my config folder when 5.0 asked.

**Comment by stax76** [comment]
Re-download it and this time don't copy over. I just tested the script, fires one time.

**Comment by SLowrAM** [comment]
I renamed my mpvnet to mpvnetold and created new folder mpvnet and extracted 7z into it, then added attached script to Scripts folder and when I press Ctrl+A I get the prompt and press OK and it re-occurs 3 more times after that..  So I had a clean install, but get the issue not sure what else to try.
[ctrla.zip](https://github.com/stax76/mpv.net/files/3439961/ctrla.zip)

**Comment by stax76** [comment]
You mean you copied the script to <startup>\scripts ?

Did you see the file readme.txt in <startup>\scripts ?

It says you should rather use <config folder>\scripts instead of <startup>\scripts .

<startup>\scripts and <startup>\extensions is only for things that ship with mpv.net, because of that you should never copy over.

How many extensions do you have in <startup>\extensions ? What is their name?

How many extensions do you have in <config folder>\extensions ? What is their name?

How many scripts do you have in <startup>\scripts ? What is their name?

How many scripts do you have in <config folder>\scripts ? What is their name?

Please read the following wiki pages:

https://github.com/stax76/mpv.net/wiki/Extensions

https://github.com/stax76/mpv.net/wiki/Scripting

You probably have multiple scripts or multiple host extensions or both.

**Comment by SLowrAM** [comment]
To do a clean test I setup a Virtual Machine running Windows 10 64bit version 1903.  I downloaded the portable v5 64bit zip file.  I extracted it to a folder c:\mpvnet.  I then copied the above ctrla.cs script into the c:\mpvnet\Scripts folder.  I then ran mpvnet.exe and chose Startup folder (c:\mpvnet) as my config folder, then I pressed Ctrl-A the messagebox popped up, I clicked Ok and it pops up again multiple times.  So I'm able to recreate this issue on a clean windows 10 machine, not sure why you're not encountering it.

**Comment by SLowrAM** [comment]
Did more testing.  Trying to better understanding your above message, FYI there is no readme.txt file in Scripts folder in portable zip packages.  
The issue seems to be that when launching v5 for the first time it asks what folder to use for config folder, you should not be allowed to choose Startup folder (i.e. c:\mpvnet) as a choice, as doing so creates the conflict of <startup>\scripts and <config folder>\scripts.  
This last test before first running mpvnet.exe v5 for first time I created the portable_config folder so it used that and no issues then when putting ctrla.cs Script in portable_config\Scripts folder.  
Thank you for better helping me understand folder structures workings.  
If someone in the popup that shows the first v5 run chooses the folder they ran mpvnet.exe from as their config folder they will encounter the script firing multiple times issue.

**Comment by stax76** [comment]
Thanks for pointing out, next release does not allow startup folder and config folder being identical.
