### ISSUE TITLE
pause-when-minimize.lua Can not be used.

### ISSUE THREAD

**Issue by 1579187773** [stax76/mpv.net#76]
Hello, I tried to put pause-when-minimize.lua in portable_config\scripts, save the video and minimize the mpv.net but can't automatically minimize the pause. How do I need to set it? The original MPV is available for normal use.

**Comment by stax76** [comment]
It's not working because mpv.net implements an own main window which results in all window related features not working unless mpv.net has an own implementation. Only very few things have an own implementation. For this task there is a C# (*.cs) script available.

https://github.com/stax76/mpv.net/wiki/Scripting#pause-when-minimize
